# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory inside the container
WORKDIR /pg-frontend

# Copy the package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN vite build

# Use nginx to serve the built React app
FROM nginx:alpine
COPY --from=0 /pg-frontend/build /usr/share/nginx/html

# Expose the port the app runs on
EXPOSE 5173

# Start nginx
CMD ["nginx", "-g", "daemon off;"]